[package]
name = "janeconverter-desktop"
version = "2.2.6"
description = "The modern JaneConverter desktop surface"
authors = ["project//aspyr"]
edition = "2021"

[lib]
name = "janeconverter_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
rand = "0.9"
rfd = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
url = "2"

[target.'cfg(windows)'.dependencies]
drag = "=2.1.1"
winreg = "0.55"
